Added build instructions
cptactionhank/docker-atlassian-jira-service-desk pull request #3
Opened 2017-01-26 10:07 UTC by isparkes

Hey, thanks for putting this Docker image together. It helped me out of a spot... ;)

I added a little bit of dox that might help others keep their image up to date.

2017-02-05 22:01 UTC, cptactionhank requested changes
I like your changes but I'm thinking perhaps moving it to a separate file since the README is used as content body on Docker Hub and to keep it and sweet.

How about `HOWTO.md` or `BUILD.md`

2017-02-05 22:01 UTC, cptactionhank commented on README.md
> +export PATH=$PATH:$(pwd)/bin
can we remove this line

2017-02-05 22:01 UTC, cptactionhank commented on README.md
> +prepare
and change this to `bin/prepare`

2017-02-05 22:04 UTC, isparkes commented
You da man.

I mostly wanted to say thanks for putting it together, it saved a stack of
time, and it was such a great job, the only little improvement was this.
Either HOWTO or BUILD would be great.

Have a good evening, and thanks!

Ian

On 5 February 2017 at 23:01, Martin Aksel Jensen <notifications@github.com>
wrote:

> *@cptactionhank* requested changes on this pull request.
>
> I like your changes but I'm thinking perhaps moving it to a separate file
> since the README is used as content body on Docker Hub and to keep it and
> sweet.
>
> How about HOWTO.md or BUILD.md
> ------------------------------
>
> In README.md
> <https://github.com/cptactionhank/docker-atlassian-jira-service-desk/pull/3#pullrequestreview-20179912>
> :
>
> > @@ -33,3 +33,20 @@ If you see out of date documentation, lack of tests, etc., you can help out by e
>  - sending a pull request with modifications (remember to read [contributing guide](https://github.com/cptactionhank/docker-atlassian-jira-service-desk/blob/master/CONTRIBUTING.md) before.)
>
>  Continuous Integration and Continuous Delivery is made possible with the great services from [GitHub](https://github.com), [Travis CI](https://travis-ci.org/), and [CircleCI](https://circleci.com/) written in [Ruby](https://www.ruby-lang.org/), using [RSpec](http://rspec.info/), [Capybara](https://jnicklas.github.io/capybara/), and [PhantomJS](http://phantomjs.org/) frameworks.
> +
> +## Building the Docker image
> +
> +JIRA Service Desk is in a period of fast development, and releases are coming thick and fast. In order to keep up to date, you might have to rebuild this image. Here are the steps to do it
> +
> +Clone the repository:
> +```git clone git@github.com:cptactionhank/docker-atlassian-jira-service-desk.git
> +cd docker-atlassian-jira-service-desk
> +export PATH=$PATH:$(pwd)/bin
>
> can we remove this line
> ------------------------------
>
> In README.md
> <https://github.com/cptactionhank/docker-atlassian-jira-service-desk/pull/3#pullrequestreview-20179912>
> :
>
> > @@ -33,3 +33,20 @@ If you see out of date documentation, lack of tests, etc., you can help out by e
>  - sending a pull request with modifications (remember to read [contributing guide](https://github.com/cptactionhank/docker-atlassian-jira-service-desk/blob/master/CONTRIBUTING.md) before.)
>
>  Continuous Integration and Continuous Delivery is made possible with the great services from [GitHub](https://github.com), [Travis CI](https://travis-ci.org/), and [CircleCI](https://circleci.com/) written in [Ruby](https://www.ruby-lang.org/), using [RSpec](http://rspec.info/), [Capybara](https://jnicklas.github.io/capybara/), and [PhantomJS](http://phantomjs.org/) frameworks.
> +
> +## Building the Docker image
> +
> +JIRA Service Desk is in a period of fast development, and releases are coming thick and fast. In order to keep up to date, you might have to rebuild this image. Here are the steps to do it
> +
> +Clone the repository:
> +```git clone git@github.com:cptactionhank/docker-atlassian-jira-service-desk.git
> +cd docker-atlassian-jira-service-desk
> +export PATH=$PATH:$(pwd)/bin
> +prepare
>
> and change this to bin/prepare
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cptactionhank/docker-atlassian-jira-service-desk/pull/3#pullrequestreview-20179912>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNTQz5gG1HSAuD7bcxUJXiVD2MX5ECTks5rZkaygaJpZM4LueG9>
> .
>

2017-02-05 22:11 UTC, cptactionhank commented
Can you update your pull request to move it to say `HOWTO.md` and commit this as well so I can merge your pull request and you get credit in the commit history?

2017-02-06 06:56 UTC, isparkes commented
Yep, will do this morning!

Ian

On 5 Feb 2017 11:12 p.m., "Martin Aksel Jensen" <notifications@github.com>
wrote:

> Can you update your pull request to move it to say HOWTO.md and commit
> this as well so I can merge your pull request and you get credit in the
> commit history?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cptactionhank/docker-atlassian-jira-service-desk/pull/3#issuecomment-277554061>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABNTQ3Qpnk5PD-kih2W1Z1HHuNNOHIv6ks5rZkkvgaJpZM4LueG9>
> .
>

2018-02-08 19:55 UTC, closed without merging